### ISSUE TITLE
[polarisation] graph-tool SBM parameters? 

### ISSUE THREAD

**Issue by ZeynepP** [medialab/corpora#14]
Hi,

Thanks for sharing your dataset. I am trying to reproduce the experiment with SBM (Hyperlinks network analysis). Could you please tell me which parameters you used with minimize_nested_blockmodel_dl function of graph-tool? Because with default params, I am getting 12 blocks. 

Bests
ZP

**Comment by Yomguithereal** [comment]
Hello @ZeynepP. I think the parameters used in the papers should be found around [here](https://github.com/medialab/polarisation-espace-public/tree/master/scripts/laroutourne). Unfortunately I don't remember where exactly. @boogheta or @jphcoi might have more details.

**Comment by boogheta** [comment]
Hello @ZeynepP,
Unfortunately my bash history doesn't go far enough to find back the commands I ran, but the whole code used is there: https://github.com/medialab/polarisation-espace-public/tree/master/scripts/laroutourne and especially here https://github.com/medialab/polarisation-espace-public/blob/master/scripts/laroutourne/laroutourne.py

Looking at it, the corresponding .state files should include the max_clusters value used if any, and I don't see it in the state file on my machine, so I guess I didn't use any and would say you can leave B_min and B_max to None.

But maybe @jphcoi has a better memory of it, and I know he ran it also within jupyternotebooks on his side, so maybe these can help verify this.

**Comment by ZeynepP** [comment]
Thanks a lot, I will check it.

**Comment by ZeynepP** [comment]
With None for B_min and B_max, I have 17 blocks with your source code.
