### ISSUE TITLE
[polarisation] Medias to consider adding

### ISSUE THREAD

**Issue by boogheta** [medialab/corpora#5]
- [ ] ~~Other agencies ? (AP, Reuters, ...)~~
- [x] SudRadio (contenus texte en ligne?)
- [x] Terrestres.org
- [x] Comparer avec la liste de l'INA ?

**Comment by boogheta** [comment]
Liste ANSES à vérifier : 

- [x] 01NET 
- [x] GENERATION NT 
- [x] LE MONDE NUMERIQUE 
- [ ] ~~HDNUMERIQUE.COM~~
- [x] BEGEEK 
- [x] FRANDROID 
- [x] FREDZONE 
- [x] 01NET LE MAGAZINE DE LA HIGH-TECH PLAISIR 
- [x] LE CAFE DU GEEK 
- [x] LES NUMERIQUES 
- [x] PRESSE-CITRON 
- [x] KULTUREGEEK.FR 
- [ ] ~~SCIENCE & VIE JUNIOR~~
- [x] CA M'INTERESSE 
- [x] SCIENCES ET AVENIR LA RECHERCHE 
- [ ] ~~SCIENCE AND TECHNOLOGY DAILY~~
- [ ] ~~CITE-SCIENCES.FR~~
- [x] FUTURA SCIENCES 
- [ ] ~~THE NEW SCIENTIST~~ 
- [x] COMMENT CA MARCHE

**Comment by Yomguithereal** [comment]
Ajouter:

- [x] esprit
- [ ] ~~blast (n'existe pas encore?)~~
- [x] le vent se lève
- [x] Front Populaire
- [x] revue ballast
- [x] jeff klak
- [x] sortiràparis
- [x] pariszigzag

**Comment by Yomguithereal** [comment]
Leave the English ones out.

**Comment by Yomguithereal** [comment]
- [x] mediavenir
