### ISSUE TITLE
[polarisation] Medias to remove or merge?

### ISSUE THREAD

**Issue by boogheta** [medialab/corpora#6]
- [x] glamourparis.com does not exist anymore and redirects to vanityfair.fr, not in the corpus, create it and merge glamour within?
- [ ] les-identitaires.com is rather a political party, with its dedicated media (novopress.com) which is also in the corpus, either merge it within or remove it?

**Comment by Yomguithereal** [comment]
We decided to leave les identitaires/novopress distinct for now.
